### ISSUE TITLE
How to install for postgres?

### ISSUE THREAD

**Issue by mase7569** [burggraf/SupaScript#1]
Looks promising! After reading the readme, still no idea how to install it.

**Comment by burggraf** [comment]
Sorry about that, we will update the documentation.  The goal is to have Supabase pre-install it so you can just toggle it on like any other extension.  For now if you know how to install an extension treat it like any extension.  If not you can just open up the sql file and run the sql on your database and you should be good to go.

**Comment by burggraf** [comment]
See updates to the docs for a new install method:

Method 1: Copy the contents of the file EASY-INSTALL-Vx.yy.SQL into a SQL window in your database and run it.
