### ISSUE TITLE
Unable to call function send_email_message using SupaScript

### ISSUE THREAD

**Issue by amanuela97** [burggraf/SupaScript#12]
so i am running the following code using supabase sql editor but i get the following error "javascript function is not found for send_email_message". README states the exec() helper functions can call functions written in (PLV8), PLPGSQL, SQL or any other supported language. Is it not working because the send_email_message is written using plpgsql or is it something else ?
the send_emaile_message function was accessed from your other repo [https://github.com/burggraf/supabase-mailer/blob/main/02_send_email_message.sql](url)

create or replace function daily_task()
returns void as $$
        exec('send_email_message', ['{
        "sender": "example@gmail.com",
        "recipient": "example@gmail.com",
        "subject": "Weather updates",
        "html_body": "html here"
        }']);
$$ language plv8;

**Comment by burggraf** [comment]
First make sure you have SupaScript installed and running, then also try running the `send_email_message` function from the sql editor directly before trying to wrap it inside another function

**Comment by burggraf** [comment]
Also see the SupaScript source for `exec`:
```
    // execute a Postgresql function
    // i.e. exec('my_function',['parm1', 123, {"item_name": "test json object"}])
    this.exec = function(function_name, parms) {
      var func = plv8.find_function(function_name);
      return func(...parms);
    }

```

**Comment by amanuela97** [comment]
The send_email_message function works as expected when called directly from the sql editor. However, when i call it inside a function written in plv8 using the helper function exec, i get the response javascript function is not found for "send_email_message". i want to be able to call it from within the function since i have some values i want to dynamically pass to the sen_email_message function.

This is how i am calling the send_email_message() function inside my function written in plv8:
` exec('send_email_message', 
['{"sender": "babyzewdie@gmail.com", "recipient": "babyzewdie@gmail.com", "subject": "test","text_body": "hi"}']);

the supascript source states 
 exec calls exactly two parameters:

-the name of the function you want to call
-an optional array of parameters you want to pass to the function
and i am passing two parameters, the function send_email_message and its argument, so i am not sure why it is not working.
`

**Comment by burggraf** [comment]
First make sure SupaScript is installed and running correctly.  Then I would create a very simple hello, world function and try calling that using exec() to see if you have everything installed correctly.

**Comment by amanuela97** [comment]
I forgot to mention but i am already executing another function that fetches weather data from an api, and that function works properly when called with the exec function like so:

`exec('get_weather', [loc]);
`
The get_weather() function was written in plv8 and it accepts a location (string) as an argument.
So the only difference between the two functions is that send_email_message() is written in plpgsql, and get_weather() in plv8, but the source says you should be able to execute postgres functions.

Lastly, i noticed there is the following line beign applied to send_email_message():
`
REVOKE EXECUTE on function public.send_email_message FROM PUBLIC;
`
So i am also wondering could this be what is potentially causing the issue ?

**Comment by burggraf** [comment]
That'll do it, yes.  For security reasons I turned off public access to the send function but you can enable it.  Good catch!  I didn't think about that.

**Comment by amanuela97** [comment]
Alright, appreciate the help.

will try and revert that access policy.
