### ISSUE TITLE
Supported by Supabase

### ISSUE THREAD

**Issue by magick93** [burggraf/SupaScript#14]
Hi @burggraf 

Do you know if there are any plans for Supabase to support / offer this in Supabase?

I hope so!

**Comment by burggraf** [comment]
You can open a GitHub discussion and ask this here:  https://github.com/supabase/supabase/discussions

But in the meantime, this is a very simple thing to install yourself if you just run the script :)

**Comment by magick93** [comment]
Thanks @burggraf 

As the creator of SupaScript, and a developer at Supabase, I would have thought you would know the answer to this.

And yes, I realize I can install it locally, but I'm wanting to know if Supabase will offer support for it.
