### ISSUE TITLE
Enable RLS on the created tables

### ISSUE THREAD

**Issue by christianfl** [burggraf/SupaScript#15]
Hello again! Thanks for this awesome extension.

Would you mind enabling RLS on the created tables in the script like this?:

```
alter table supascript_log enable row level security;
alter table supascript_js_modules enable row level security;
```

I guess it wouldn't be that nice to have these in the public schema without RLS. Thanks in advance! Best wishes, Christian

**Comment by burggraf** [comment]
Yep -- good point.  Done, and released as 1.5.
Note this will change the security on your functions if they are called by `anon` or `authenticated` users.
