### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by clouedoc** [burggraf/SupaScript#16]
Hello there,

I'm trying to install SupaScript on my PostgreSQL server.

I am using the [supabase/postgres](https://github.com/supabase/postgres/) because it comes with nice extensions pre-installed. (v14)

I ran the EASY-INSTALL script (removing the last line to avoid errors).

I will document the fix I'll find here

**Comment by burggraf** [comment]
Are you running this in the Supabase dashboard, or some other way?

**Comment by clouedoc** [comment]
I'm using a GUI client (Postico v1).

To reproduce the bug:

1. Spin up `supabase/postgres`
2. Run the EASY-INSTALL script (remove the last line to avoid errors)
3. Run the testing SQL line

```sql
DO $$
    const _ = require('https://cdn.jsdelivr.net/npm/underscore@1.12.1/underscore-min.js');
    const retval = _.map([1, 2, 3], function(num){ return num * 3; });
    return retval;
$$ language plv8;
```
_Testing SQL line_

You will get a message like this:

```
ERROR:  ReferenceError: require is not defined
CONTEXT:  undefined() LINE 2:     const _ = require('https://cdn.jsdelivr.net/npm/underscore@1.12.1/underscore-min.js');
```

**Fix**

Closing and reopening the GUI client fixes the issue.
I tried to reproduce the big a third time but it didn't work.
Maybe adding `SELECT pg_reload_conf();` to the end of the installation script would help?
Adding a warning in the README.md would also have helped

**Comment by burggraf** [comment]
Thanks for posting your fix here.  It's generally recommended that you run this in the Supabase dashboard, as SQL run there runs under a `superuser` context.  But glad you got it working with Postico.
