### ISSUE TITLE
How to import btoa and atob

### ISSUE THREAD

**Issue by Torres1080** [burggraf/SupaScript#17]
I'm trying to import them on my project and could not find the way. Adding some example as documentación inside the repo would be nice.

Thanks in advance.

**Comment by burggraf** [comment]
See this page that has an example:   [https://github.com/burggraf/SupaScript/blob/main/docs/http.md](https://github.com/burggraf/SupaScript/blob/main/docs/http.md)

```js
const base64lib = require('https://raw.githubusercontent.com/davidchambers/Base64.js/master/base64.js');
const encoded = base64lib.btoa('api:key-00000000000000000000000000000000');
```

**Comment by Torres1080** [comment]
Thanks Mark!
