### ISSUE TITLE
Does SupaScript work with PLV8 3.0?

### ISSUE THREAD

**Issue by shah** [burggraf/SupaScript#6]
This seems like a great library, nice work! I was curious if SupaScript works with the latest PLV8 3.0 that was recently released. 

Thanks!

**Comment by burggraf** [comment]
@shah We're currently using PLV8 version 3.0alpha with Supabase, so I think so.

**Comment by shah** [comment]
That's great to hear, @burggraf - are you experimenting or are you using SupaScript and PLV8 in production? I'm super-excited about being able to use JavaScript for stored procedures and functions but was curious about your opinions about stability. Right now we have dozens of PostgreSQL PL/pgSQL stored routines and many PL/Python stored routines but would love to use PL/v8 stored routines at our earliest opportunity!

**Comment by burggraf** [comment]
PLV8 has been around a long time and should definitely be production ready.  SupaScript is just a wrapper that adds a few features to PLV8, so you should be fine to use it in production.  Look over the SupaScript source if you have any questions -- it's pretty short.
