### ISSUE TITLE
Error while creating SUPASCRIPT extension

### ISSUE THREAD

**Issue by asharabu** [burggraf/SupaScript#7]
Hi,

I am getting the below error while trying to create SUPASCRIPT extension.

> 
test111=# CREATE EXTENSION SUPASCRIPT CASCADE;
ERROR:  extension "supascript" has no installation script nor update path for version "1.4"

> 

![image](https://user-images.githubusercontent.com/42669995/121996737-c6f38980-cdc6-11eb-8b48-c9c7f101b67f.png)

**Comment by burggraf** [comment]
The SupaScript extension is not installed on your system.  Intead, use method #1 to install:

`Method 1: Copy the contents of the file EASY-INSTALL-Vx.yy.SQL into a SQL window in your database and run it.`

[EASY-INSTALL-V1.4.SQL](https://github.com/burggraf/SupaScript/blob/main/EASY-INSTALL-V1.4.SQL)

**Comment by asharabu** [comment]
> The SupaScript extension is not installed on your system. Intead, use method 1 to install:
> 
> `Method 1: Copy the contents of the file EASY-INSTALL-Vx.yy.SQL into a SQL window in your database and run it.`
> 
> [EASY-INSTALL-V1.4.SQL](https://github.com/burggraf/SupaScript/blob/main/EASY-INSTALL-V1.4.SQL)

@burggraf We are using normal PostgreSQL database instead of supabase PostgreSQL. So can we use method 1 can you confirm?.
When I tried to restore the  EASY-INSTALL-V1.4.SQL file got below error,

> 
postgres@test:~$ psql testabc < EASY-INSTALL-V1.4.SQL
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  function supascript_init() does not exist, skipping
DROP FUNCTION
SET
ALTER DATABASE
ERROR:  function uuid_generate_v4() does not exist
LINE 3:     id uuid primary key default uuid_generate_v4(),
                                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
CREATE TABLE
CREATE FUNCTION
ERROR:  publication "supabase_realtime" does not exist

> 

I have executed the below command to create `uuid-ossp` extension and again tried to restore now I am getting the below error,

> 
postgres@test:~$ psql testabc < EASY-INSTALL-V1.4.SQL
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  function supascript_init() does not exist, skipping
DROP FUNCTION
SET
ALTER DATABASE
CREATE TABLE
CREATE TABLE
CREATE FUNCTION
ERROR:  publication "supabase_realtime" does not exist

>

**Comment by burggraf** [comment]
Ah, good catch on UUID-OSSP, that's also required.  I'dd add it to the install script!

You're good to go now.  If you're not using Supabase, you can comment out:

`ALTER PUBLICATION supabase_realtime ADD TABLE supascript_log;`

Or just ignore that error.  You just don't get access to the realtime client-side debugging stuff if you're not on Supabase, but everything should work fine.

**Comment by asharabu** [comment]
> Ah, good catch on UUID-OSSP, that's also required. I'dd add it to the install script!
> 
> You're good to go now. If you're not using Supabase, you can comment out:
> 
> `ALTER PUBLICATION supabase_realtime ADD TABLE supascript_log;`
> 
> Or just ignore that error. You just don't get access to the realtime client-side debugging stuff if you're not on Supabase, but everything should work fine.

@burggraf But I am still getting the same error.

> 
postgres@test:~$ psql testabc < EASY-INSTALL-V1.4.SQL
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  function supascript_init() does not exist, skipping
DROP FUNCTION
SET
ALTER DATABASE
CREATE TABLE
CREATE TABLE
CREATE FUNCTION
postgres@test:~$ psql
psql (13.2 (Ubuntu 13.2-1.pgdg18.04+1))
Type "help" for help.

postgres=# \c testabc
You are now connected to database "testabc" as user "postgres".
testabc=# \dx
                                         List of installed extensions
   Name    | Version |   Schema   |                                Description
-----------+---------+------------+----------------------------------------------------------------------------
 http      | 1.4     | public     | HTTP client for PostgreSQL, allows web page retrieval inside the database.
 plpgsql   | 1.0     | pg_catalog | PL/pgSQL procedural language
 plv8      | 3.0.0   | pg_catalog | PL/JavaScript (v8) trusted procedural language
 uuid-ossp | 1.1     | public     | generate universally unique identifiers (UUIDs)
(4 rows)

testabc=# CREATE EXTENSION SUPASCRIPT CASCADE;
ERROR:  extension "supascript" has no installation script nor update path for version "1.4"

>

**Comment by burggraf** [comment]
You don't need to create the extension.  It's already installed.  All the extension does is run the script you already ran, so basically it's an automated process.

Try running a sample script from the `examples` folder and see if it's running ok for you now.

**Comment by shah** [comment]
Thanks @burggraf can you confirm that SupaScript should not show up in the list of installed extensions?

```
List of installed extensions
Name | Version | Schema | Description
-----------+---------+------------+----------------------------------------------------------------------------
http | 1.4 | public | HTTP client for PostgreSQL, allows web page retrieval inside the database.
plpgsql | 1.0 | pg_catalog | PL/pgSQL procedural language
plv8 | 3.0.0 | pg_catalog | PL/JavaScript (v8) trusted procedural language
uuid-ossp | 1.1 | public | generate universally unique identifiers (UUIDs)
==> should SupaScript show here?
```

**Comment by burggraf** [comment]
Correct.  It's technically **not** an extension unless it's loaded as one through your file system.  It's really more just an extension of the plv8 extension in this case.  It'll work exactly the same way if you load it using the EASY-INSTALL-Vx.yy.SQL script.

**Comment by razakpm** [comment]
We have executed EASY-INSTALL-V1.4.SQL and tried to execute 

> create or replace function test_momentjs()
> returns json as $$
>     const moment = require('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.js', false);
>     const retval = moment().add(7, 'days');    
>     return retval; 
> $$ language plv8;

and when we tried 

> select test_momentjs();

failed with error SQL Error [XX000]: ERROR: ReferenceError: require is not defined
  Where: test_momentjs() LINE 2:     const moment = require('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.js', true);

**Comment by burggraf** [comment]
Is your database name `posgres`?  The EASY_INSTALL script assumes it is,  if not, you need to change it in the script.

**Comment by razakpm** [comment]
Database name was different and tried ALTER DATABASE {NEW_POSTGRES_NAME} SET PLV8.START_PROC TO 'supascript_init';
but we are getting the same error.

**Comment by burggraf** [comment]
Did you try to restart postgresql?

**Comment by razakpm** [comment]
Now we tried, then the Error changed, New error is

**Comment by burggraf** [comment]
Yes, to clear cache:

```sql
DELETE FROM SUPASCRIPT_JS_MODULES;
``` 

What  PLV8 version do you have installed?

```sql
SELECT PLV8_VERSION()
```

**Comment by burggraf** [comment]
The new error is from the HTTP extension.  Are you sure it's installed and working?
From the EASY_INSTALL SCRIPT:

```sql
CREATE EXTENSION IF NOT EXISTS HTTP;
```

**Comment by burggraf** [comment]
Also check your PostgreSQL version:

```sql
SELECT VERSION()
```

We use PostgreSQL 12.6

**Comment by razakpm** [comment]
HTTP Extension is available
PLV8_Version 3.0.0
PostgreSQL Version 

> PostgreSQL 13.2 (Ubuntu 13.2-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

**Comment by priyadarshiniguptan** [comment]
> Now we tried, then the Error changed, New error is
> 
> > SQL Error [XX000]: ERROR: Could not load module through http: NULL {"sqlerrcode":"XX000","schema_name":null,"table_name":null,"column_name":null,"datatype_name":null,"constraint_name":null,"detail":null,"hint":null,"context":"SQL statement "SELECT content FROM http_get('NULL');"","internalquery":null,"code":2600}
> > Where: supascript_init() LINE 116:                 plv8.elog(ERROR, `Could not load module through http: NULL`, JSON.stringify(err));
> 

Looking at this error , especially the statement "SELECT content FROM http_get('NULL');", looks like the http extension may not be the issue. The module or the url that is being looked up is passed as NULL into the http_get() method in the supascript_init() function and hence the exception.

**Comment by burggraf** [comment]
The function content is loaded on line 145:

```js
plv8.execute(`SELECT content FROM http_get('${module}');`)[0].content;
```

I would suggest you manually try an `http_get` call and see if that's working for you first.

My environment is PLV8 3.0.0alpha and PostgreSQL 12.6, so I'm not sure what might be different for you.  Also note that not all libraries work -- so try to stay within the ones in the examples folder first.

**Comment by burggraf** [comment]
Start with something simple like:

```sql
SELECT content FROM http_get('https://google.com')
```

To see if you can fetch content.

**Comment by razakpm** [comment]
http_get call manually and SELECT content FROM http_get('https://google.com') all succeeded , but the above error still exists, the passed value getting as Null inside.

**Comment by burggraf** [comment]
@razakpm Have you tried any more of the examples?  Do they all give the same error?

**Comment by priyadarshiniguptan** [comment]
> Start with something simple like:
> 
> ```sql
> SELECT content FROM http_get('https://google.com')
> ```
> 
> To see if you can fetch content.

Yes we are able to fetch content for the following -
`select content from http_get('https://cdn.jsdelivr.net/npm/underscore@1.12.1/underscore-min.js') `- this works
`SELECT content FROM http_get('https://google.com')` - this works
`SELECT content FROM http_get('https://unpkg.com/mustache@latest');`  - this works as well

Manually running http_get seems to work fine.

**Comment by burggraf** [comment]
Have you tried any other examples from:  [https://github.com/burggraf/SupaScript/tree/main/examples](https://github.com/burggraf/SupaScript/tree/main/examples)?

**Comment by priyadarshiniguptan** [comment]
Yes I did run all of the examples now again and I think I got what the issue is. Sometimes the http_get() seems to be timing out. I tried using  `SELECT http_set_curlopt('CURLOPT_TIMEOUT_MS', '60000');` - everything works just fine.

Thanks for all the support!

One last question - Does superscript support multi database postgres cluster? So if I have to install supascript in two databases within the same instance can I run the EASY INSATLL script in both databases and give a restart?

**Comment by burggraf** [comment]
Glad you got your issue resolved -- it must be a connectivity issue with your network.  Great job tracking that down!

Yes, you can run the EASY INSTALL on multiple databases.  Just comment out that last line if you're not using Supabase and you can re-run the script on any server at any time.

**Comment by priyadarshiniguptan** [comment]
Great! Thanks a lot. We will keep you posted with any other issues that we may see.

**Comment by burggraf** [comment]
Also let me know if you come up with ideas for new features.

**Comment by shah** [comment]
Be careful what you ask for @burggraf, we'll probably take you up on that offer of new features! 😄

**Comment by burggraf** [comment]
Sweet!
