### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by althaf004** [burggraf/SupaScript#8]
Hi, i was trying to implement plv8 functions to the DB. the script was created successfully. But trying to test the plv8 with the examples, i happen to get an error, 

SQL Error [XX000]: ERROR: ReferenceError: require is not defined
  Where: test_momentjs() LINE 3:     const moment = require('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.js', true);
  
  Please help me to resolve this error. i have attached the file i run,

[supascript.txt](https://github.com/burggraf/SupaScript/files/6762507/supascript.txt)

**Comment by burggraf** [comment]
1. Are you running inside of a Supabase instance, or in your own PostgreSQL environment?
2. Do you get any errors when you run the [EASY INSTALL SCRIPT](https://github.com/burggraf/SupaScript/blob/main/EASY-INSTALL-V1.4.SQL)?  (You can comment out the last line of the script if you need to.)

**Comment by althaf004** [comment]
1.Are you running inside of a Supabase instance, or in your own PostgreSQL environment?
i`m running in PostgreSQL 

2.Do you get any errors when you run the EASY INSTALL SCRIPT? (You can comment out the last line of the script if you need to.)
i have excluded the command and run, still same.

Please see the attachment, for the script which i had run.

**Comment by burggraf** [comment]
Did you ever get this resolved?
