### ISSUE TITLE
Throwing errors and relating them to HTTP status codes

### ISSUE THREAD

**Issue by thomasgrastein** [burggraf/SupaScript#9]
Hello!

I've been experimenting with data validation through SupaScript functions, but I don't seem to understand how I can control the status code of the response. If an error is thrown from PLV8 it will result in status code 500, and plv8.elog does not seem to willingly output what I want. I was thinking, that it could be cool if an error was thrown from PLV8/SupaScript, they could be some way to define what PostgreSQL error code it should raise, to have it work better with Postgrest (https://postgrest.org/en/v7.0.0/api.html#http-logic).

I know that functions are not necessarily called through Postgrest, but with Supabase, it would make sense to support this connection.

Is there some way to do it that I haven't figured out yet?

**Comment by thomasgrastein** [comment]
Found a solution:
Created a separate plpgsql function to throw errors.

**Comment by m0ast** [comment]
I dunno if this helps but I got around with javascript.
```js
  function state_helper(c) {
    if (!c || !(c.constructor === String) || c.length != 5) return null;
    let res = 0;
    const zero_cp = "0".charCodeAt(0);
    for (let i = 0; i < c.length; i++) {
      const codeAt = c.charCodeAt(i) - zero_cp;
      if (codeAt > 0x3f) return null;
      res += (codeAt & 0x3f) << (i * 6);
    }
    return res;
  }

  class PgError extends Error {
    constructor({ message, code, detail, hint }, ...params) {
      super(message, ...params);

      this.code = state_helper(code);
      this.detail = detail;
      this.hint = hint;
    }
  }

  throw new PgError({
    message: "FooMessage",
    detail: "foo",
    code: "09000",
  });
```

**Comment by burggraf** [comment]
@m0ast This is pretty amazing code.  I wonder if we should try to incorporate this into the core of SupaScript?

**Comment by m0ast** [comment]
@burggraf it could be a nice addition though I'm not sure it will integrate nicely with `console` (see #10).
I had to dig in the source around [here](https://github.com/plv8/plv8/blob/f36d09/plv8.cc#L2122) where any unhandled exception goes through. Maybe plv8 maintainers didn't intend this way around?
plv8 exporting `erepport` would be great.
